export interface ToneOption {
  id: string;
  label: string;
  icon: string;
  prompt: string;
}

export const TONE_OPTIONS: ToneOption[] = [
  {
    id: "normal",
    label: "Normal",
    icon: "💬",
    prompt: "Usa un tono neutro, claro y directo. Ni formal ni informal. Responde de manera equilibrada: una definición precisa seguida de un ejemplo concreto. Sin adornos, sin frases motivacionales, sin estructura de clase. Solo la información necesaria, bien expresada.",
  },
  {
    id: "academico",
    label: "Académico",
    icon: "📖",
    prompt: "Adopta el estilo de un paper académico o un libro de texto universitario. Usa terminología técnica precisa y no la simplifiques. Estructura la respuesta con definición formal, fundamento teórico y contexto dentro del campo. Menciona limitaciones, matices y relaciones con otros conceptos del área. Evita coloquialismos. El tono debe ser impersonal, riguroso y denso en contenido. No uses frases como 'imagina que...' o 'es como si...'.",
  },
  {
    id: "profesional",
    label: "Profesional",
    icon: "💼",
    prompt: "Adopta el tono de un consultor senior hablando con un directivo. Ve directo al valor: qué es, qué problema resuelve, qué impacto tiene en el negocio y qué decisión debería tomar el usuario. Usa lenguaje ejecutivo: conciso, orientado a ROI, riesgos y oportunidades. Evita explicaciones largas. Si hay una recomendación clara, dala. El usuario no tiene tiempo que perder.",
  },
  {
    id: "didactico",
    label: "Didáctico",
    icon: "🎓",
    prompt: "Eres un profesor paciente explicando a alguien que aprende por primera vez. Empieza siempre con una analogía del mundo real antes de usar el término técnico. Luego introduce el concepto gradualmente. Usa frases como 'piénsalo así:', 'un ejemplo sencillo sería:', 'la diferencia clave es:'. El objetivo es que el concepto quede grabado, no solo entendido.",
  },
  {
    id: "informal",
    label: "Informal",
    icon: "😊",
    prompt: "Habla como un amigo que sabe mucho de IA explicándote algo en un café. Usa lenguaje cotidiano, contracciones, ejemplos de la vida diaria y un tono relajado. Puedes usar expresiones como 'básicamente', 'o sea', 'la idea es que...'. Nada de jerga innecesaria. Si algo es complicado, admítelo con humor y búscale la vuelta más simple. El objetivo es que la persona se sienta cómoda preguntando cualquier cosa.",
  },
  {
    id: "mentor",
    label: "Mentor",
    icon: "🚀",
    prompt: "Eres un mentor que conoce bien el campo profesional del usuario y quiere ayudarle a crecer. No te limites a explicar el concepto: conecta ese conocimiento con el desarrollo profesional del usuario, señala por qué es estratégico aprenderlo ahora, y sugiere un próximo paso concreto que pueda dar. Usa un tono cálido, directo y motivador. Celebra la curiosidad.",
  },
];

export interface Sector {
  id: string;
  label: string;
  icon: string;
}

export const SECTORS: Sector[] = [
  { id: "construccion", label: "Construcción", icon: "🏗️" },
  { id: "medioambiente", label: "Medio ambiente", icon: "🌿" },
  { id: "salud", label: "Salud", icon: "🏥" },
  { id: "tecnologia", label: "Tecnología", icon: "💻" },
  { id: "finanzas", label: "Finanzas / Banca", icon: "🏦" },
  { id: "educacion", label: "Educación", icon: "📚" },
  { id: "manufactura", label: "Manufactura", icon: "🏭" },
  { id: "comercio", label: "Comercio / Retail", icon: "🛒" },
  { id: "gobierno", label: "Gobierno / Público", icon: "🏛️" },
  { id: "legal", label: "Legal / Jurídico", icon: "⚖️" },
  { id: "logistica", label: "Logística", icon: "🚚" },
  { id: "agroindustria", label: "Agroindustria", icon: "🌾" },
];

export interface GlossaryTerm {
  id: string;
  term: string;
  category: string;
  shortDefinition: string;
  relatedTerms: string[];
}

export interface UserProfile {
  profession: string;
  label: string;
  icon: string;
  systemPromptContext: string;
}

export const USER_PROFILES: UserProfile[] = [
  {
    profession: "medico",
    label: "Médico / Profesional de la salud",
    icon: "🏥",
    systemPromptContext:
      "El usuario es médico o profesional de la salud. Usa analogías con diagnósticos, registros de pacientes, flujos clínicos y gestión hospitalaria. Relaciona los conceptos de IA con aplicaciones en salud como diagnóstico asistido, análisis de imágenes médicas, resumen de historiales clínicos o asistentes de prescripción.",
  },
  {
    profession: "ingeniero",
    label: "Ingeniero / Desarrollador",
    icon: "⚙️",
    systemPromptContext:
      "El usuario es ingeniero o desarrollador de software. Usa terminología técnica precisa, habla de APIs, pipelines, arquitecturas de sistemas, code review automatizado, CI/CD y automatización de procesos de desarrollo. Puedes usar pseudocódigo o ejemplos técnicos.",
  },
  {
    profession: "abogado",
    label: "Abogado / Profesional legal",
    icon: "⚖️",
    systemPromptContext:
      "El usuario es abogado o trabaja en el ámbito legal. Usa analogías con contratos, due diligence, revisión de documentos legales, análisis de jurisprudencia y gestión de casos. Relaciona la IA con aplicaciones como revisión contractual automatizada, búsqueda legal y redacción de documentos.",
  },
  {
    profession: "educador",
    label: "Educador / Docente",
    icon: "🎓",
    systemPromptContext:
      "El usuario es educador o docente. Usa analogías con planes de estudio, evaluación de estudiantes, personalización del aprendizaje y gestión del aula. Relaciona la IA con tutoría personalizada, generación de contenido educativo, evaluación automática y asistentes de aprendizaje.",
  },
  {
    profession: "marketing",
    label: "Marketing / Ventas",
    icon: "📊",
    systemPromptContext:
      "El usuario trabaja en marketing o ventas. Usa analogías con campañas, segmentación de clientes, generación de leads, copywriting y análisis de métricas. Relaciona la IA con generación de contenido, personalización de mensajes, análisis de sentimiento y automatización de campañas.",
  },
  {
    profession: "financiero",
    label: "Finanzas / Contabilidad",
    icon: "💰",
    systemPromptContext:
      "El usuario trabaja en finanzas o contabilidad. Usa analogías con análisis financiero, auditoría, gestión de riesgos y reportes. Relaciona la IA con detección de fraude, análisis predictivo, automatización de reportes contables y asistentes de inversión.",
  },
  {
    profession: "rrhh",
    label: "Recursos Humanos",
    icon: "👥",
    systemPromptContext:
      "El usuario trabaja en recursos humanos. Usa analogías con procesos de selección, evaluación de desempeño, onboarding y cultura organizacional. Relaciona la IA con screening de CVs, entrevistas asistidas, análisis de engagement y automatización de procesos de RRHH.",
  },
  {
    profession: "otro",
    label: "Otro / General",
    icon: "🌐",
    systemPromptContext:
      "El usuario tiene un perfil general o no especificado. Usa ejemplos cotidianos y claros, evita jerga técnica excesiva. Relaciona los conceptos con situaciones del día a día en el trabajo.",
  },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: "adaptive-thinking",
    term: "Adaptive Thinking",
    category: "Razonamiento",
    shortDefinition: "Capacidad del modelo para decidir dinámicamente cuánto razonamiento interno requiere una tarea.",
    relatedTerms: ["extended-thinking", "llm", "parametros-temperatura"],
  },
  {
    id: "adversarial-ai",
    term: "Adversarial AI",
    category: "Seguridad",
    shortDefinition: "El uso de entradas o técnicas maliciosas diseñadas para engañar, manipular o explotar modelos de IA.",
    relatedTerms: ["jailbreak", "inyeccion-prompts", "ai-red-teaming", "data-poisoning"],
  },
  {
    id: "agente-ia",
    term: "Agente de IA",
    category: "Agentes",
    shortDefinition: "Sistema de IA capaz de tomar decisiones autónomas, usar herramientas externas y actuar para alcanzar objetivos con mínima intervención humana.",
    relatedTerms: ["function-calling", "human-in-the-loop", "langchain"],
  },
  {
    id: "ai-explainability",
    term: "AI Explainability",
    category: "Gobernanza / Modelos",
    shortDefinition: "La capacidad de interpretar, comprender y explicar cómo un modelo de IA toma sus decisiones o predicciones.",
    relatedTerms: ["evals", "aibom", "bias-ia"],
  },
  {
    id: "ai-red-teaming",
    term: "AI Red Teaming",
    category: "Seguridad",
    shortDefinition: "Pruebas sistemáticas que simulan ataques adversarios para identificar vulnerabilidades y fallos en IA antes de su despliegue.",
    relatedTerms: ["adversarial-ai", "jailbreak", "aispm"],
  },
  {
    id: "aibom",
    term: "AIBOM (AI Bill of Materials)",
    category: "Gobernanza / Seguridad",
    shortDefinition: "Un inventario detallado de los componentes, conjuntos de datos y dependencias que forman un sistema de IA.",
    relatedTerms: ["aispm", "ai-explainability", "bias-ia"],
  },
  {
    id: "aispm",
    term: "AISPM",
    category: "Seguridad",
    shortDefinition: "La evaluación y mejora continua de la postura de seguridad y de gobernanza relacionada con los modelos de IA de una organización.",
    relatedTerms: ["dspm", "aibom", "ai-red-teaming"],
  },
  {
    id: "ajuste-fine-tuning",
    term: "Ajuste (Fine-tuning)",
    category: "Entrenamiento",
    shortDefinition: "Proceso de entrenar adicionalmente un modelo preentrenado con datos específicos para adaptar su estilo o dominio.",
    relatedTerms: ["pretraining", "rlhf", "lora", "peft"],
  },
  {
    id: "alucinacion",
    term: "Alucinación (Hallucination)",
    category: "Seguridad / Modelos",
    shortDefinition: "Fallo donde el modelo de IA genera información que suena plausible pero que es fácticamente incorrecta o inventada.",
    relatedTerms: ["rag", "grounding", "hhh"],
  },
  {
    id: "artifacts",
    term: "Artifacts",
    category: "Funcionalidad",
    shortDefinition: "Funcionalidad de Claude que crea contenido independiente (código, sitios web, diagramas) en una ventana separada.",
    relatedTerms: ["claude-sonnet", "system-prompt"],
  },
  {
    id: "batch-api",
    term: "Batch API",
    category: "API / Costos",
    shortDefinition: "Interfaz que procesa solicitudes de forma asíncrona en un plazo de 24 horas a cambio de un descuento del 50%.",
    relatedTerms: ["tokens", "prompt-caching", "llm"],
  },
  {
    id: "bert",
    term: "BERT",
    category: "Modelos",
    shortDefinition: "Modelo de lenguaje basado en codificadores preentrenado bidireccionalmente para capturar contextos a la izquierda y derecha de cada palabra.",
    relatedTerms: ["transformer", "llm", "self-attention"],
  },
  {
    id: "bias-ia",
    term: "Bias en IA",
    category: "Gobernanza / Datos",
    shortDefinition: "Errores sistémicos y resultados injustos o sesgados en la IA debido a la forma en que fue diseñada o los datos con que fue entrenada.",
    relatedTerms: ["rlhf", "aibom", "ai-explainability"],
  },
  {
    id: "bloom",
    term: "BLOOM",
    category: "Modelos",
    shortDefinition: "Gran modelo de lenguaje open-source entrenado para ejecutar tareas de entendimiento y generación en múltiples idiomas.",
    relatedTerms: ["llm", "gpt", "foundation-model"],
  },
  {
    id: "chatgpt",
    term: "ChatGPT",
    category: "Modelos / Agentes",
    shortDefinition: "Asistente y producto conversacional de OpenAI que funciona sobre la arquitectura de los modelos GPT.",
    relatedTerms: ["gpt", "llm", "copilot"],
  },
  {
    id: "chunking",
    term: "Chunking",
    category: "Datos",
    shortDefinition: "Estrategias para dividir grandes porciones de datos en pedazos indexables en una base de datos vectorial.",
    relatedTerms: ["embeddings", "vector-database", "rag"],
  },
  {
    id: "claude-code",
    term: "Claude Code",
    category: "Modelos / Herramientas",
    shortDefinition: "Herramienta de línea de comandos (CLI) de Claude para tareas de ingeniería y edición de bases de código completas.",
    relatedTerms: ["claude-sonnet", "agente-ia", "function-calling"],
  },
  {
    id: "claude-haiku",
    term: "Claude Haiku",
    category: "Modelos",
    shortDefinition: "El modelo más rápido y económico de la familia Claude, optimizado para tareas de alta velocidad.",
    relatedTerms: ["claude-sonnet", "claude-opus", "tokens"],
  },
  {
    id: "claude-opus",
    term: "Claude Opus",
    category: "Modelos",
    shortDefinition: "El modelo más inteligente y capaz de la familia Claude, diseñado para razonamiento complejo y tareas de agentes.",
    relatedTerms: ["claude-haiku", "claude-sonnet", "extended-thinking"],
  },
  {
    id: "claude-sonnet",
    term: "Claude Sonnet",
    category: "Modelos",
    shortDefinition: "El modelo de equilibrio ideal entre velocidad e inteligencia, estándar para la mayoría de aplicaciones de producción.",
    relatedTerms: ["claude-haiku", "claude-opus", "llm"],
  },
  {
    id: "clip",
    term: "CLIP",
    category: "Multimodalidad",
    shortDefinition: "Modelo de visión-lenguaje entrenado para asociar y comprender relaciones profundas entre imágenes y su descripción en texto.",
    relatedTerms: ["multimodal-ai", "embeddings", "diffusion"],
  },
  {
    id: "copilot",
    term: "Copilot",
    category: "Productividad / Agentes",
    shortDefinition: "Asistentes de IA de Microsoft diseñados para ayudar en tareas en aplicaciones de desarrollo o trabajo de oficina.",
    relatedTerms: ["chatgpt", "llm", "agente-ia"],
  },
  {
    id: "dark-ai",
    term: "Dark AI",
    category: "Seguridad",
    shortDefinition: "El uso malicioso o poco ético de tecnologías de IA en el desarrollo de actividades cibercriminales y campañas de desinformación.",
    relatedTerms: ["jailbreak", "inyeccion-prompts", "deepfake"],
  },
  {
    id: "data-poisoning",
    term: "Data Poisoning",
    category: "Seguridad / Datos",
    shortDefinition: "Estrategia de ataque donde datos maliciosos son inyectados deliberadamente en el set de entrenamiento de la IA.",
    relatedTerms: ["adversarial-ai", "bias-ia", "dspm"],
  },
  {
    id: "deep-learning",
    term: "Deep Learning",
    category: "Básicos / Arquitectura",
    shortDefinition: "Subcampo del aprendizaje automático que usa redes neuronales de múltiples capas para identificar patrones complejos en los datos.",
    relatedTerms: ["neural-network", "machine-learning", "transformer"],
  },
  {
    id: "deepfake",
    term: "Deepfake",
    category: "Seguridad / Multimodalidad",
    shortDefinition: "Medios sintéticos hiperrealistas donde la imagen, video o voz de una persona se suplanta usando aprendizaje automático.",
    relatedTerms: ["dark-ai", "multimodal-ai", "generative-ai"],
  },
  {
    id: "diffusion",
    term: "Diffusion (Difusión)",
    category: "Arquitectura / Multimodalidad",
    shortDefinition: "Modelos generativos que parten de ruido aleatorio y aprenden a 'limpiarlo' inversamente para generar un resultado estructurado.",
    relatedTerms: ["generative-ai", "espacio-latente", "clip"],
  },
  {
    id: "dpo",
    term: "Direct Preference Optimization (DPO)",
    category: "Entrenamiento de Modelos",
    shortDefinition: "Técnica de alineación eficiente que ajusta los modelos para preferir respuestas humanas usando pares de datos etiquetados.",
    relatedTerms: ["rlhf", "reinforcement-learning", "ajuste-fine-tuning"],
  },
  {
    id: "dspm",
    term: "DSPM (Data Security Posture Management)",
    category: "Seguridad / Datos",
    shortDefinition: "Proceso continuo para vigilar y mejorar la protección de información confidencial en cargas de trabajo de IA.",
    relatedTerms: ["aispm", "data-poisoning", "bias-ia"],
  },
  {
    id: "elicitation",
    term: "Elicitation",
    category: "Protocolos (MCP)",
    shortDefinition: "Capacidad de un servidor MCP para solicitar información adicional o aclaraciones al usuario durante una tarea.",
    relatedTerms: ["mcp", "mcp-server", "mcp-client", "sampling"],
  },
  {
    id: "embeddings",
    term: "Embeddings",
    category: "Arquitectura",
    shortDefinition: "Representación numérica de datos (vectores) que captura relaciones semánticas entre palabras o imágenes.",
    relatedTerms: ["vector-database", "rag", "chunking"],
  },
  {
    id: "espacio-latente",
    term: "Espacio Latente (Latent Space)",
    category: "Arquitectura",
    shortDefinition: "Representación matemática en un espacio multidimensional comprimido donde los modelos codifican características significativas de los datos.",
    relatedTerms: ["embeddings", "diffusion", "quantization"],
  },
  {
    id: "evals",
    term: "Evals (Evaluaciones)",
    category: "Gobernanza / Modelos",
    shortDefinition: "Pruebas y marcos de validación para analizar el rendimiento, la fiabilidad y la seguridad de un modelo frente a puntos de referencia.",
    relatedTerms: ["ai-explainability", "ai-red-teaming", "llm"],
  },
  {
    id: "extended-thinking",
    term: "Extended Thinking",
    category: "Razonamiento",
    shortDefinition: "Característica que permite a Claude razonar paso a paso internamente antes de generar una respuesta visible.",
    relatedTerms: ["adaptive-thinking", "claude-opus", "tokens"],
  },
  {
    id: "few-shot-prompting",
    term: "Few-shot Prompting",
    category: "Prompting",
    shortDefinition: "Técnica de incluir ejemplos específicos en la instrucción para guiar el formato o tono de la respuesta.",
    relatedTerms: ["one-shot-prompting", "zero-shot-prompting", "in-context-learning"],
  },
  {
    id: "foundation-model",
    term: "Foundation Model (Modelo Fundacional)",
    category: "Modelos",
    shortDefinition: "Sistemas generalistas de IA entrenados en volúmenes masivos de datos diversos, base para ser afinados a numerosas tareas.",
    relatedTerms: ["llm", "pretraining", "ajuste-fine-tuning"],
  },
  {
    id: "function-calling",
    term: "Function Calling",
    category: "APIs / Agentes",
    shortDefinition: "Característica que permite al modelo generar datos estructurados para invocar herramientas o APIs externas.",
    relatedTerms: ["agente-ia", "tool-poisoning", "mcp"],
  },
  {
    id: "generative-ai",
    term: "Generative AI",
    category: "Básicos",
    shortDefinition: "Clase de inteligencia artificial especializada en producir nuevos contenidos como imágenes, código, sonido y textos a partir de patrones previos.",
    relatedTerms: ["llm", "gpt", "diffusion"],
  },
  {
    id: "gpt",
    term: "GPT (Generative Pre-trained Transformer)",
    category: "Modelos",
    shortDefinition: "Familia de redes neuronales basadas en la arquitectura Transformer, preentrenadas a gran escala para generalizar sobre textos.",
    relatedTerms: ["llm", "transformer", "chatgpt"],
  },
  {
    id: "grounding",
    term: "Grounding (Fundamentación)",
    category: "Arquitectura",
    shortDefinition: "Proceso de conectar las respuestas del modelo con fuentes de información externas verificables.",
    relatedTerms: ["rag", "embeddings", "vector-database"],
  },
  {
    id: "hhh",
    term: "HHH (Helpful, Honest, Harmless)",
    category: "Gobernanza / Ética",
    shortDefinition: "Marco ético de Anthropic: Útil (cumple tareas), Honesto (no alucina) e Inofensivo (no es ofensivo).",
    relatedTerms: ["alucinacion", "jailbreak", "ai-red-teaming"],
  },
  {
    id: "human-in-the-loop",
    term: "Human-in-the-Loop",
    category: "Seguridad",
    shortDefinition: "Estrategia de seguridad donde se requiere aprobación humana antes de ejecutar acciones críticas.",
    relatedTerms: ["agente-ia", "sandboxing", "shadow-ai"],
  },
  {
    id: "in-context-learning",
    term: "In-context Learning",
    category: "Prompting",
    shortDefinition: "Capacidad del LLM de adaptar su respuesta aprendiendo un patrón desde los ejemplos en el prompt sin actualizar sus pesos.",
    relatedTerms: ["few-shot-prompting", "one-shot-prompting", "zero-shot-prompting"],
  },
  {
    id: "inferencia",
    term: "Inferencia (Inference)",
    category: "Operaciones",
    shortDefinition: "Momento en que se procesan datos de entrada usando un modelo ya entrenado para obtener una predicción o salida.",
    relatedTerms: ["tokens", "latencia", "ttft", "llm"],
  },
  {
    id: "inyeccion-prompts",
    term: "Inyección de Prompts",
    category: "Seguridad",
    shortDefinition: "Vulnerabilidad donde instrucciones maliciosas camufladas manipulan al modelo para ignorar sus reglas.",
    relatedTerms: ["jailbreak", "tool-poisoning", "system-prompt"],
  },
  {
    id: "jailbreak",
    term: "Jailbreak (IA)",
    category: "Seguridad",
    shortDefinition: "Esfuerzo intencionado de formular comandos engañosos para forzar al modelo a evadir sus controles de seguridad.",
    relatedTerms: ["inyeccion-prompts", "tool-poisoning", "adversarial-ai"],
  },
  {
    id: "langchain",
    term: "LangChain",
    category: "APIs / Arquitectura",
    shortDefinition: "Marco de desarrollo popular para simplificar la creación de aplicaciones con LLMs, orquestando memorias y recuperando datos.",
    relatedTerms: ["rag", "llm", "agente-ia"],
  },
  {
    id: "latencia",
    term: "Latencia",
    category: "Rendimiento",
    shortDefinition: "Tiempo que transcurre desde que se envía una instrucción hasta que el modelo comienza a responder (TTFT).",
    relatedTerms: ["ttft", "tokens", "prompt-caching"],
  },
  {
    id: "llm",
    term: "LLM (Large Language Model)",
    category: "Modelos",
    shortDefinition: "Modelo de IA entrenado en vastas cantidades de texto para comprender y generar lenguaje humano.",
    relatedTerms: ["gpt", "transformer", "tokens", "foundation-model"],
  },
  {
    id: "lora",
    term: "LoRA (Low-Rank Adaptation)",
    category: "Entrenamiento de Modelos",
    shortDefinition: "Estrategia eficiente para ajustar un modelo enorme mediante la inserción de diminutas matrices entrenables mientras congela el resto.",
    relatedTerms: ["ajuste-fine-tuning", "qlora", "peft"],
  },
  {
    id: "machine-learning",
    term: "Machine Learning (ML)",
    category: "Básicos",
    shortDefinition: "Esfera de la IA orientada al diseño de algoritmos que aprenden de datos progresivamente y mejoran su rendimiento sin instrucciones explícitas.",
    relatedTerms: ["deep-learning", "neural-network", "llm"],
  },
  {
    id: "mcp",
    term: "MCP (Model Context Protocol)",
    category: "Protocolos",
    shortDefinition: "Protocolo abierto que estandariza cómo las aplicaciones proporcionan contexto y herramientas a los LLMs.",
    relatedTerms: ["mcp-client", "mcp-server", "mcp-connector"],
  },
  {
    id: "mcp-client",
    term: "MCP Client",
    category: "Arquitectura",
    shortDefinition: "Aplicación que aloja al LLM y gestiona la conexión con los servidores MCP (ej: Claude Desktop).",
    relatedTerms: ["mcp", "mcp-server", "elicitation"],
  },
  {
    id: "mcp-connector",
    term: "MCP Connector",
    category: "Ecosistema Claude",
    shortDefinition: "Característica que permite conectarse a servidores MCP directamente desde la Messages API sin construir un cliente MCP independiente.",
    relatedTerms: ["mcp", "mcp-client", "function-calling"],
  },
  {
    id: "mcp-server",
    term: "MCP Server",
    category: "Arquitectura",
    shortDefinition: "Servicio que expone herramientas, recursos o prompts específicos a un cliente MCP.",
    relatedTerms: ["mcp", "mcp-client", "roots", "sampling"],
  },
  {
    id: "mixture-of-experts",
    term: "Mixture of Experts (MoE)",
    category: "Arquitectura",
    shortDefinition: "Arquitectura de red neuronal con 'expertos' especializados, de los cuales solo se activa un subconjunto según el input.",
    relatedTerms: ["transformer", "llm", "foundation-model"],
  },
  {
    id: "model-theft",
    term: "Model Theft (Robo de Modelo)",
    category: "Seguridad",
    shortDefinition: "Extracción o replicación sin autorización del modelo de IA o de sus parámetros para replicar sistemas ajenos.",
    relatedTerms: ["adversarial-ai", "dark-ai", "jailbreak"],
  },
  {
    id: "multimodal-ai",
    term: "Multi-Modal AI",
    category: "Multimodalidad",
    shortDefinition: "Tipo de IA construida para recibir, interpretar y emitir simultáneamente varios formatos de datos como textos, audios e imágenes.",
    relatedTerms: ["clip", "llm", "diffusion"],
  },
  {
    id: "neural-network",
    term: "Neural Network (Red Neuronal)",
    category: "Arquitectura",
    shortDefinition: "Modelos algorítmicos fundamentados en el cerebro humano que enlazan capas de nodos para descifrar relaciones complejas.",
    relatedTerms: ["deep-learning", "transformer", "machine-learning"],
  },
  {
    id: "nlp",
    term: "NLP (Natural Language Processing)",
    category: "Básicos",
    shortDefinition: "Campo interdisciplinario para lograr que las computadoras entiendan, procesen e interactúen en idiomas humanos.",
    relatedTerms: ["llm", "embeddings", "bert"],
  },
  {
    id: "one-shot-prompting",
    term: "One-Shot Prompting",
    category: "Prompting",
    shortDefinition: "Configurar el contexto del LLM ingresando una sola ilustración perfecta de entrada-salida para que capte qué formato seguir.",
    relatedTerms: ["few-shot-prompting", "zero-shot-prompting", "in-context-learning"],
  },
  {
    id: "peft",
    term: "Parameter-Efficient Fine-Tuning (PEFT)",
    category: "Entrenamiento de Modelos",
    shortDefinition: "Enfoques que adaptan modelos genéricos alterando solo una porción diminuta de los parámetros de entrenamiento.",
    relatedTerms: ["lora", "qlora", "ajuste-fine-tuning"],
  },
  {
    id: "parametros-temperatura",
    term: "Parámetros (Temperature)",
    category: "Prompting",
    shortDefinition: "Variables que controlan el comportamiento del modelo, como el nivel de aleatoriedad o creatividad.",
    relatedTerms: ["llm", "prompt-engineering", "inferencia"],
  },
  {
    id: "pretraining",
    term: "Pretraining (Preentrenamiento)",
    category: "Entrenamiento / Modelos",
    shortDefinition: "Proceso inicial de entrenar un modelo en un enorme corpus de texto sin etiquetar para que aprenda a predecir la siguiente palabra.",
    relatedTerms: ["ajuste-fine-tuning", "foundation-model", "rlhf"],
  },
  {
    id: "prompt-caching",
    term: "Prompt Caching",
    category: "Rendimiento / Costos",
    shortDefinition: "Almacenamiento de partes frecuentes de una instrucción para reutilizarlas, reduciendo costos hasta un 90%.",
    relatedTerms: ["tokens", "latencia", "batch-api"],
  },
  {
    id: "prompt-engineering",
    term: "Prompt Engineering",
    category: "Prompting",
    shortDefinition: "Proceso iterativo de diseñar y optimizar instrucciones para obtener los mejores resultados de la IA.",
    relatedTerms: ["few-shot-prompting", "system-prompt", "xml-tags"],
  },
  {
    id: "qlora",
    term: "QLoRA",
    category: "Entrenamiento de Modelos",
    shortDefinition: "Integración del enfoque LoRA con cuantización intensiva (usualmente a 4-bit) para reducir exponencialmente el peso en memoria.",
    relatedTerms: ["lora", "peft", "quantization"],
  },
  {
    id: "quantization",
    term: "Quantization (Cuantización)",
    category: "Arquitectura",
    shortDefinition: "Proceso técnico para acelerar modelos reduciendo los bits que los representan, disminuyendo el tamaño del modelo final.",
    relatedTerms: ["qlora", "slm", "tokens"],
  },
  {
    id: "rag",
    term: "RAG (Retrieval Augmented Generation)",
    category: "Arquitectura",
    shortDefinition: "Técnica que recupera datos externos relevantes y los inserta en el contexto del modelo antes de responder.",
    relatedTerms: ["embeddings", "vector-database", "grounding"],
  },
  {
    id: "reinforcement-learning",
    term: "Reinforcement Learning (Aprendizaje por Refuerzo)",
    category: "Entrenamiento de Modelos",
    shortDefinition: "Estrategia donde un agente virtual aprende dinámicamente a elegir acciones recibiendo recompensas o castigos del entorno.",
    relatedTerms: ["rlhf", "dpo", "ajuste-fine-tuning"],
  },
  {
    id: "rlhf",
    term: "RLHF",
    category: "Entrenamiento",
    shortDefinition: "Aprendizaje por refuerzo a partir de retroalimentación humana para alinear el modelo con preferencias humanas.",
    relatedTerms: ["ajuste-fine-tuning", "dpo", "reinforcement-learning"],
  },
  {
    id: "roots",
    term: "Roots",
    category: "Seguridad",
    shortDefinition: "Mecanismo de seguridad en MCP que define las fronteras de acceso del servidor al sistema de archivos.",
    relatedTerms: ["mcp-server", "sandboxing", "human-in-the-loop"],
  },
  {
    id: "sampling",
    term: "Sampling",
    category: "Protocolos (MCP)",
    shortDefinition: "Capacidad de un servidor MCP para pedirle al LLM del cliente que complete una tarea de generación.",
    relatedTerms: ["mcp-server", "elicitation", "llm"],
  },
  {
    id: "sandboxing",
    term: "Sandboxing",
    category: "Seguridad",
    shortDefinition: "Entorno aislado que limita las capacidades de ejecución de una herramienta para proteger el sistema anfitrión.",
    relatedTerms: ["roots", "human-in-the-loop", "adversarial-ai"],
  },
  {
    id: "self-attention",
    term: "Self-Attention",
    category: "Arquitectura",
    shortDefinition: "Dinámica central en la estructura Transformer donde cada token establece asociaciones matemáticas con todos los demás de una frase.",
    relatedTerms: ["transformer", "bert", "llm"],
  },
  {
    id: "shadow-ai",
    term: "Shadow AI",
    category: "Seguridad / Gobernanza",
    shortDefinition: "Uso inseguro y clandestino de utilidades de IA por empleados dentro de la infraestructura empresarial eludiendo controles de TI.",
    relatedTerms: ["aispm", "dark-ai", "human-in-the-loop"],
  },
  {
    id: "slm",
    term: "Small Language Models (SLM)",
    category: "Modelos",
    shortDefinition: "Modelos lingüísticos reducidos y optimizados para funciones puntuales y operaciones rápidas con muy pocos recursos.",
    relatedTerms: ["llm", "quantization", "ajuste-fine-tuning"],
  },
  {
    id: "system-prompt",
    term: "System Prompt",
    category: "Prompting",
    shortDefinition: "Instrucción de alto nivel que define el rol, tono y reglas permanentes de la IA en una conversación.",
    relatedTerms: ["prompt-engineering", "inyeccion-prompts", "xml-tags"],
  },
  {
    id: "tokens",
    term: "Tokens",
    category: "Arquitectura / Costos",
    shortDefinition: "Unidad básica de procesamiento de texto (aprox. 3.5 caracteres). El modelo factura y procesa por tokens.",
    relatedTerms: ["llm", "ventana-contexto", "prompt-caching", "batch-api"],
  },
  {
    id: "tool-poisoning",
    term: "Tool Poisoning",
    category: "Seguridad",
    shortDefinition: "Tipo de inyección de prompt donde se ocultan instrucciones maliciosas en los metadatos o descripciones de herramientas.",
    relatedTerms: ["inyeccion-prompts", "adversarial-ai", "function-calling"],
  },
  {
    id: "transformer",
    term: "Transformer",
    category: "Arquitectura",
    shortDefinition: "Fundamento estructural de IA (2017) que analiza bloques enteros de información paralelamente mediante 'atención'.",
    relatedTerms: ["bert", "gpt", "self-attention", "llm"],
  },
  {
    id: "ttft",
    term: "TTFT (Time to First Token)",
    category: "Métricas / Rendimiento",
    shortDefinition: "Métrica de rendimiento que mide el tiempo exacto que tarda un modelo en empezar a escribir su respuesta.",
    relatedTerms: ["latencia", "inferencia", "prompt-caching"],
  },
  {
    id: "vector-database",
    term: "Vector Database",
    category: "Datos",
    shortDefinition: "Repositorios diseñados para guardar vectores (embeddings) y realizar consultas de proximidad semántica.",
    relatedTerms: ["embeddings", "rag", "chunking"],
  },
  {
    id: "ventana-contexto",
    term: "Ventana de Contexto",
    category: "Arquitectura",
    shortDefinition: "Cantidad máxima de información (tokens) que el modelo puede 'recordar' y procesar en una sola vez.",
    relatedTerms: ["tokens", "llm", "rag"],
  },
  {
    id: "vibe-coding",
    term: "Vibe Coding",
    category: "Productividad / Workflows",
    shortDefinition: "Nuevo enfoque de software donde se desarrollan programas instruyendo objetivos al agente de IA con voz o texto simple, sin codificar manualmente.",
    relatedTerms: ["agente-ia", "claude-code", "prompt-engineering"],
  },
  {
    id: "xml-tags",
    term: "XML Tags",
    category: "Prompting",
    shortDefinition: "Etiquetas estructuradas (ej: <input>) que ayudan a Claude a distinguir entre instrucciones, datos y ejemplos.",
    relatedTerms: ["system-prompt", "prompt-engineering", "few-shot-prompting"],
  },
  {
    id: "zero-shot-prompting",
    term: "Zero-Shot Prompting",
    category: "Prompting",
    shortDefinition: "Indicarle una orden al modelo sin facilitarle ningún par de ejemplos o pre-entrenamiento de antemano.",
    relatedTerms: ["one-shot-prompting", "few-shot-prompting", "in-context-learning"],
  },
];
